Config file enhancements
BrowserStackCE/percy-pdf pull request #6
Opened 2023-07-20 08:30 UTC by samirans89

- Config File enhancements -> Getting started scenarios vs Advanced scenarios
  - Multiple project folders at one go
  - Options for includeDocs and excludeDocs within the project folder
  - Include / Exclude PDF pages of Docs under `specialDocConfigs`
- Working directory changed to `.dist`
- Adding Windows compatibility. Unix / Mac already working.
- Using pdfjs-dist npm package to read PDF page count programmatically

2023-08-25 11:15 UTC, samirans89 commented on helpers/utils.js
> +    return spawnSync(command, args, options)
`spawnsnyc` is called for with a hardcoded `percy snapshot` prefix, in this code base. 
The config file for Percy snapshot is dynamic but also generated through the same codebase. User does not have flexibility to provide the snapshot config file directly.

2023-08-25 11:16 UTC, samirans89 commented on helpers/utils.js
> +        fs.unlink(path.join(dir, file), (err) => {
The codebase uses this function to empty the `.dist` directory used by the codebase to store temporary files.

2023-08-25 11:16 UTC, samirans89 commented on helpers/utils.js
> +        fs.unlink(path.join(dir, file), (err) => {
The codebase uses this function to empty the .dist directory used by the codebase to store temporary files.

2023-10-12 18:13 UTC, ansel2000 requested changes
Minor comments for changes in README.md

2023-10-12 18:13 UTC, ansel2000 commented on README.md
>   3. Create an account on [Percy](https://percy.io) and create a new project. Note the Project specific `PERCY_TOKEN`, as this will be required while triggering the project builds.
We can specify a **Percy Web** project to avoid any confusion

2023-10-12 18:13 UTC, ansel2000 commented on package.json
> +        "start-server": "npx forever start \"node_modules/http-server/bin/http-server\" \"-s\" \"-p 8080\" \"pdfjs-3.4.120-dist\"",
Since this command is being executed in run.js is the start-server expected to be used by the user anywhere? I think we can remove this if not being used.

2024-06-20 12:57 UTC, samirans89 commented on README.md
>   3. Create an account on [Percy](https://percy.io) and create a new project. Note the Project specific `PERCY_TOKEN`, as this will be required while triggering the project builds.
making this change.

2024-06-20 12:59 UTC, samirans89 commented on package.json
> +        "start-server": "npx forever start \"node_modules/http-server/bin/http-server\" \"-s\" \"-p 8080\" \"pdfjs-3.4.120-dist\"",
removing

2024-06-24 14:32 UTC, ansel2000 approved these changes

2024-06-24 14:33 UTC, merged